import { Inter } from 'next/font/google'
import { config } from '@fortawesome/fontawesome-svg-core';

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  config.autoAddCss = false;

  return (
    <html lang="en">
       <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" />

        <style>
          
        </style>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
